version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'karty_db'
      MYSQL_USER: 'karty_user'
      MYSQL_PASSWORD: 'karty_pass'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    ports:
      - 3306:3306
    networks:
      - karty
  cache:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - karty
    command: redis-server --save 20 1 --loglevel warning --requirepass default1
    volumes:
      - cache:/data
networks:
  karty:
    driver: bridge
volumes:
  cache:
    driver: local